name: Deploy static content to Pages

on:
  push:
    branches: ['master']

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: 'npm'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Get KoGmaps Submodule Hash
        id: submodule-hash
        run: echo "hash=$(git submodule status public/maps | awk '{print $1}')" >> $GITHUB_OUTPUT
      - name: Cache KoGmaps Submodule
        id: cache-submodule
        uses: actions/cache@v4
        with:
          path: public/maps
          key: ${{ runner.os }}-kogmaps-${{ steps.submodule-hash.outputs.hash }}
      - name: Update KoGmaps Submodule
        if: steps.cache-submodule.outputs.cache-hit != 'true'
        run: git submodule update --init --depth 1 public/maps
      - name: Install dependencies & run script
        run: npm ci && python parse_maps.py
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          # Upload dist folder
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
